name: Build WebApp Preview
on:
  pull_request:
    branches:
      - webapp
  push:
    branches:
      - webapp

jobs:
  master:
    if: "! startsWith(github.event.head_commit.message, '[CI Skip]')"
    name: Deploy WebApp Preview
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_PAT }}
    - name: Build WebApp
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'
      env:
        TRANSAK_API_KEY: ${{ secrets.TRANSAK_API_KEY }}
        BANXA_SANDBOX_API_KEY: ${{ secrets.BANXA_SANDBOX_API_KEY }}
        BANXA_SANBOX_API_SECRET: ${{ secrets.BANXA_SANBOX_API_SECRET }}
      run: |
        yarn install --immutable | grep -v 'YN0013'
        yarn webapp:build
    - name: Publish to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        accountId: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        projectName: ${{ vars.CLOUDFLARE_PAGES_PROJECT_NAME }}
        directory: './packages/webapp/build'
        gitHubToken: ${{ secrets.GH_PAT_BOT }}
        wranglerVersion: '3'
